import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { HiArrowLeft } from 'react-icons/hi';

export default function PrivacyPolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <section className="pt-28 pb-20 bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Back link */}
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-primary hover:text-primary-dark text-sm font-medium mb-8 transition-colors"
        >
          <HiArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        {/* Header */}
        <div className="mb-12">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Privacy Policy
          </h1>
          <p className="text-gray-500">
            <strong>Effective Date:</strong> 25th May 2018
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-lg max-w-none text-gray-600 space-y-8">
          <p>
            Wirral Carpet Cleaning Limited (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates
            the <a href="https://www.wirralcarpetcleaning.com" className="text-primary hover:text-primary-dark">www.wirralcarpetcleaning.com</a> website
            and the page &ldquo;Wirral Carpet Cleaning LTD&rdquo; on Facebook (the &ldquo;Service&rdquo;).
          </p>
          <p>
            This page informs you of our policies regarding the collection, use, and disclosure of personal
            data when you use our Service and the choices you have associated with that data.
          </p>
          <p>
            We use your data to provide and improve the Service. By using the Service, you agree to the
            collection and use of information in accordance with this policy. Unless otherwise defined in
            this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms
            and Conditions, accessible
            from <a href="https://www.wirralcarpetcleaning.com" className="text-primary hover:text-primary-dark">www.wirralcarpetcleaning.com</a>.
          </p>

          {/* Definitions */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Definitions</h2>

          <h3 className="text-xl font-semibold text-gray-800">Personal Data</h3>
          <p>
            Personal Data means data about a living individual who can be identified from those data
            (or from those and other information either in our possession or likely to come into our possession).
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Usage Data</h3>
          <p>
            Usage Data is data collected automatically either generated by the use of the Service or from
            the Service infrastructure itself (for example, the duration of a page visit).
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Cookies</h3>
          <p>Cookies are small pieces of data stored on a User&rsquo;s device.</p>

          <h3 className="text-xl font-semibold text-gray-800">Data Controller</h3>
          <p>
            Data Controller means a person who (either alone or jointly or in common with other persons)
            determines the purposes for which and the manner in which any personal data are, or are to be, processed.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Data Processor</h3>
          <p>
            Data Processor (or Service Provider) means any person (other than an employee of the Data Controller)
            who processes the data on behalf of the Data Controller. We may use the services of various Service
            Providers in order to process your data more effectively.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Data Subject</h3>
          <p>Data Subject is any living individual who is the subject of Personal Data.</p>

          <h3 className="text-xl font-semibold text-gray-800">User</h3>
          <p>
            The User is the individual using our Service. The User corresponds to the Data Subject, who is
            the subject of Personal Data.
          </p>

          {/* Information Collection */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Information Collection and Use</h2>
          <p>
            We collect several different types of information for various purposes to provide and improve
            our Service to you.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Personal Data</h3>
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable
            information that can be used to contact or identify you (&ldquo;Personal Data&rdquo;). Personally
            identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <p>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials
            and other information that may be of interest to you. You may opt out of receiving any, or all, of
            these communications from us by contacting us.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Usage Data</h3>
          <p>
            We may also collect information how the Service is accessed and used (&ldquo;Usage Data&rdquo;).
            This Usage Data may include information such as your computer&rsquo;s Internet Protocol address
            (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique device identifiers and other
            diagnostic data.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Location Data</h3>
          <p>
            We may use and store information about your location if you give us permission to do so
            (&ldquo;Location Data&rdquo;). We use this data to provide features of our Service, to improve
            and customise our Service.
          </p>
          <p>
            You can enable or disable location services when you use our Service at any time, through your
            device settings.
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Tracking Cookies Data</h3>
          <p>
            We use cookies and similar tracking technologies to track the activity on our Service and hold
            certain information.
          </p>
          <p>
            Cookies are files with small amount of data which may include an anonymous unique identifier.
            Cookies are sent to your browser from a website and stored on your device. Tracking technologies
            also used are beacons, tags, and scripts to collect and track information and to improve and
            analyse our Service.
          </p>
          <p>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
            However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
          </ul>

          {/* Use of Data */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Use of Data</h2>
          <p>Wirral Carpet Cleaning Limited uses the collected data for various purposes:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
          </ul>

          {/* Retention */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Retention of Data</h2>
          <p>
            Wirral Carpet Cleaning Limited will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the
            extent necessary to comply with our legal obligations (for example, if we are required to retain
            your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p>
            Wirral Carpet Cleaning Limited will also retain Usage Data for internal analysis purposes. Usage Data
            is generally retained for a shorter period of time, except when this data is used to strengthen the
            security or to improve the functionality of our Service, or we are legally obligated to retain this
            data for longer time periods.
          </p>

          {/* Transfer */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Transfer of Data</h2>
          <p>
            Your information, including Personal Data, may be transferred to — and maintained on — computers
            located outside of your state, province, country or other governmental jurisdiction where the data
            protection laws may differ than those from your jurisdiction.
          </p>
          <p>
            If you are located outside United Kingdom and choose to provide information to us, please note that
            we transfer the data, including Personal Data, to United Kingdom and process it there.
          </p>
          <p>
            Your consent to this Privacy Policy followed by your submission of such information represents your
            agreement to that transfer.
          </p>
          <p>
            Wirral Carpet Cleaning Limited will take all steps reasonably necessary to ensure that your data is
            treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will
            take place to an organisation or a country unless there are adequate controls in place including the
            security of your data and other personal information.
          </p>

          {/* Disclosure */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Disclosure of Data</h2>

          <h3 className="text-xl font-semibold text-gray-800">Disclosure for Law Enforcement</h3>
          <p>
            Under certain circumstances, Wirral Carpet Cleaning Limited may be required to disclose your
            Personal Data if required to do so by law or in response to valid requests by public authorities
            (e.g. a court or a government agency).
          </p>

          <h3 className="text-xl font-semibold text-gray-800">Legal Requirements</h3>
          <p>
            Wirral Carpet Cleaning Limited may disclose your Personal Data in the good faith belief that such
            action is necessary to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Wirral Carpet Cleaning Limited</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>

          {/* Security */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Security of Data</h2>
          <p>
            The security of your data is important to us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>

          {/* Your Rights */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Your Rights</h2>
          <p>
            Wirral Carpet Cleaning Limited aims to take reasonable steps to allow you to correct, amend, delete,
            or limit the use of your Personal Data.
          </p>
          <p>
            Whenever made possible, you can update your Personal Data directly within your account settings section.
            If you are unable to change your Personal Data, please contact us to make the required changes.
          </p>
          <p>
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from
            our systems, please contact us.
          </p>
          <p>In certain circumstances, you have the right:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>To access and receive a copy of the Personal Data we hold about you</li>
            <li>To rectify any Personal Data held about you that is inaccurate</li>
            <li>To request the deletion of Personal Data held about you</li>
          </ul>
          <p>
            You have the right to data portability for the information you provide to Wirral Carpet Cleaning Limited.
            You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you
            can manage and move it.
          </p>
          <p>Please note that we may ask you to verify your identity before responding to such requests.</p>

          {/* Service Providers */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Service Providers</h2>
          <p>
            We may employ third party companies and individuals to facilitate our Service (&ldquo;Service
            Providers&rdquo;), to provide the Service on our behalf, to perform Service-related services or to
            assist us in analysing how our Service is used.
          </p>
          <p>
            These third parties have access to your Personal Data only to perform these tasks on our behalf and
            are obligated not to disclose or use it for any other purpose.
          </p>

          {/* Links */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Links to Other Sites</h2>
          <p>
            Our Service may contain links to other sites that are not operated by us. If you click on a third party
            link, you will be directed to that third party&rsquo;s site. We strongly advise you to review the Privacy
            Policy of every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of
            any third party sites or services.
          </p>

          {/* Children */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Children&rsquo;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13 (&ldquo;Children&rdquo;).
          </p>
          <p>
            We do not knowingly collect personally identifiable information from anyone under the age of 13. If you
            are a parent or guardian and you are aware that your child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data from children without verification of
            parental consent, we take steps to remove that information from our servers.
          </p>

          {/* Changes */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
            Privacy Policy on this page.
          </p>
          <p>
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
            effective and update the &ldquo;effective date&rdquo; at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
          </p>

          {/* Contact */}
          <h2 className="text-2xl font-bold text-gray-900 !mt-12">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>By email: <a href="mailto:contact@wirralcarpetcleaning.com" className="text-primary hover:text-primary-dark">contact@wirralcarpetcleaning.com</a></li>
            <li>By visiting our website: <a href="https://www.wirralcarpetcleaning.com/contact-us" className="text-primary hover:text-primary-dark">wirralcarpetcleaning.com/contact-us</a></li>
            <li>By calling us on <a href="tel:01519369664" className="text-primary hover:text-primary-dark">0151 936 9664</a> / <a href="tel:07724564683" className="text-primary hover:text-primary-dark">07724 564 683</a></li>
          </ul>
        </div>
      </div>
    </section>
  );
}
